### ISSUE TITLE
Metrics and monitoring

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#4]
### Tasks
- [ ] Needs analysis to understand what is currently being sent to Datadog, and how the data is used.
- [ ] Evaluate whether prometheus can serve this need, and decide which tool we are using for user-facing metrics
- [ ] Implement a daemonset to emit events to our chosen metrics tool.

**Comment by mgreensmith** [comment]
Current sources:
-cloudwatch events into datadog
- dd-agent daemonset
-custom statsd emitter sending redis key stats to dd-agent

**Comment by mgreensmith** [comment]
We like prometheus:
-we can scrape specific cloudwatch metrics into prometheus
-we have options for getting deep redis data

**Comment by mgreensmith** [comment]
#34, #35, #36
